### ISSUE TITLE
Update from deprecated upstream failure

### ISSUE THREAD

**Issue by bill-redman** [pantheon-systems/terminus-conversion-tools-plugin#60]
I've tried to run the conversion:update-from-deprecated-upstream on 2 different sites.  In each case the process failed.  Following is the error and stack trace from one of those sites:

$ terminus conversion:update-from-deprecated-upstream imaging-services-d9

 An existing local site repository found in "/Users/billredman/imaging-services-d9".
Do you want to proceed with it (a temporary copy will be cloned otherwise)? (yes/no) [yes]:
 > 

 [notice] Local git repository path is set to "/Users/billredman/imaging-services-d9".
 [notice] Creating "conversion" git branch based on "drupal-recommended" upstream...
 [notice] Copying site-specific files...
 [notice] Site-specific files have been copied
 [notice] Updating composer.json to match "drupal-composer-managed" upstream...
PHP Fatal error:  Uncaught Error: Call to a member function getMessage() on null in /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/pantheon-systems/terminus-conversion-tools-plugin/src/Commands/ConvertToDrupalRecommendedSiteCommand.php:114
Stack trace:
#0 [internal function]: Pantheon\TerminusConversionTools\Commands\ConvertToDrupalRecommendedSiteCommand->convert('imaging-service...', Array)
#1 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Command/Command.php(298): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Users/billredman/terminus/terminus/src/Terminus.php(480): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\Console\Application), Array)
#11 phar:///Users/billredman/terminus/terminus/bin/terminus(79): Pantheon\Terminus\Terminus->run()
#12 /Users/billredman/terminus/terminus(12): require('phar:///Users/b...')
#13 {main}
  thrown in /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/pantheon-systems/terminus-conversion-tools-plugin/src/Commands/ConvertToDrupalRecommendedSiteCommand.php on line 114

Fatal error: Uncaught Error: Call to a member function getMessage() on null in /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/pantheon-systems/terminus-conversion-tools-plugin/src/Commands/ConvertToDrupalRecommendedSiteCommand.php:114
Stack trace:
#0 [internal function]: Pantheon\TerminusConversionTools\Commands\ConvertToDrupalRecommendedSiteCommand->convert('imaging-service...', Array)
#1 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Command/Command.php(298): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Users/billredman/terminus/terminus/src/Terminus.php(480): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\Console\Application), Array)
#11 phar:///Users/billredman/terminus/terminus/bin/terminus(79): Pantheon\Terminus\Terminus->run()
#12 /Users/billredman/terminus/terminus(12): require('phar:///Users/b...')
#13 {main}
  thrown in /Users/billredman/.terminus/terminus-dependencies-8f30ee04b5/vendor/pantheon-systems/terminus-conversion-tools-plugin/src/Commands/ConvertToDrupalRecommendedSiteCommand.php on line 114

I don't know what the error means so I don't know where to begin looking for a resolution.  Any information/suggestions would be most welcome.

**Comment by rwagner00** [comment]
Hello! I just tested the updater on a clean upstream and all appears well there. The error and where it's occurring lead me to suspect that there's an issue with Terminus locally for you. With that in mind, a few things to check: 

1. Check the local version of PHP and ensure that it's compatible with the version of Terminus you're using. 
2. Ensure Terminus and the Conversion Tool are up to date. 
3. Re-clone the site repo and verify that the composer.json file is valid 

If none of the above works, could you please post the versions of PHP/Terminus/Conversion tool you're running? Thank you!

**Comment by bill-redman** [comment]
Hi.  Thank you for your suggestions.  I'm currently on vacation, but as soon as I return I will follow up on them.

**Comment by kporras07** [comment]
Hi @bill-redman I was looking at this and noticed that we had a long due tag to create so I went ahead and created a new tag in this plugin. Could you please update/reinstall your plugin and try again? Even if it doesn't fix your error, I expect it will show you a clearer error.

Thanks!

**Comment by jsulz** [comment]
Hi @bill-redman just wanted to check in and see if you were able to resolve your issue or get clearer error output.

**Comment by bill-redman** [comment]
Hi @jsulz.  I have not yet had the chance to get back to this.  Since returning from vacation other projects have taken precedence.
